In [3]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

In [4]:
df_url = pd.read_csv('/home/ancientsoftware/iot-threat-detector/data/phishing_site_urls.csv')

print(df_url.shape)
print(df_url.columns.tolist())
print(df_url['Label'].value_counts())
df_url.head()

(549346, 2)
['URL', 'Label']
Label
good    392924
bad     156422
Name: count, dtype: int64

                                                 URL Label
0  nobell.it/70ffb52d079109dca5664cce6f317373782/...   bad
1  www.dghjdgf.com/paypal.co.uk/cycgi-bin/webscrc...   bad
2  serviciosbys.com/paypal.cgi.bin.get-into.herf....   bad
3  mail.printakid.com/www.online.americanexpress....   bad
4  thewhiskeydregs.com/wp-content/themes/widescre...   bad

In [5]:
import os
print(os.getcwd())

/home/ancientsoftware/iot-threat-detector

In [12]:
df_url['url_length'] = df_url['URL'].str.len()
df_url['num_dots'] = df_url['URL'].str.count(".")
df_url[['URL', 'url_length', 'num_dots']].head()

                                                 URL  url_length  num_dots
0  nobell.it/70ffb52d079109dca5664cce6f317373782/...         225       225
1  www.dghjdgf.com/paypal.co.uk/cycgi-bin/webscrc...          81        81
2  serviciosbys.com/paypal.cgi.bin.get-into.herf....         177       177
3  mail.printakid.com/www.online.americanexpress....          60        60
4  thewhiskeydregs.com/wp-content/themes/widescre...         116       116

In [15]:
df_url['num_hyphens'] = df_url['URL'].str.count("-")
df_url[['URL','num_hyphens']].head()

                                                 URL  num_hyphens
0  nobell.it/70ffb52d079109dca5664cce6f317373782/...            4
1  www.dghjdgf.com/paypal.co.uk/cycgi-bin/webscrc...            2
2  serviciosbys.com/paypal.cgi.bin.get-into.herf....            1
3  mail.printakid.com/www.online.americanexpress....            0
4  thewhiskeydregs.com/wp-content/themes/widescre...            1

In [16]:
df_url['URL'].str.split('.').head()

0    [nobell, it/70ffb52d079109dca5664cce6f31737378...
1    [www, dghjdgf, com/paypal, co, uk/cycgi-bin/we...
2    [serviciosbys, com/paypal, cgi, bin, get-into,...
3    [mail, printakid, com/www, online, americanexp...
4    [thewhiskeydregs, com/wp-content/themes/widesc...
Name: URL, dtype: object

In [38]:
df_url['TLD'] = df_url['URL'].str.split('.').str[-1]
df_url[['URL', 'TLD']].head()

,URL,TLD
0,nobell.it/70ffb52d079109dca5664cce6f317373782/...,1&login_access=1322408526
1,www.dghjdgf.com/paypal.co.uk/cycgi-bin/webscrc...,php
2,serviciosbys.com/paypal.cgi.bin.get-into.herf....,dispatch35463256rzr321654641dsf654321874/href/...
3,mail.printakid.com/www.online.americanexpress....,html
4,thewhiskeydregs.com/wp-content/themes/widescre...,com/wp-content/themes/widescreen/includes/temp...

In [39]:
import math
from collections import Counter

def calculate_entropy(string):
    counts = Counter(string)
    length = len(string)
    probabilities = [count / length for count in counts.values()]
    entropy = -sum(p * math.log2(p) for p in probabilities)
    return entropy

In [40]:
df_url['entropy'] = df_url['URL'].apply(calculate_entropy)