In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

In [2]:
df_url = pd.read_csv('/home/ancientsoftware/iot-threat-detector/data/phishing_site_urls.csv')

print(df_url.shape)
print(df_url.columns.tolist())
print(df_url['Label'].value_counts())
df_url.head()

(549346, 2)
['URL', 'Label']
Label
good    392924
bad     156422
Name: count, dtype: int64

                                                 URL Label
0  nobell.it/70ffb52d079109dca5664cce6f317373782/...   bad
1  www.dghjdgf.com/paypal.co.uk/cycgi-bin/webscrc...   bad
2  serviciosbys.com/paypal.cgi.bin.get-into.herf....   bad
3  mail.printakid.com/www.online.americanexpress....   bad
4  thewhiskeydregs.com/wp-content/themes/widescre...   bad

In [3]:
import os
print(os.getcwd())

/home/ancientsoftware/iot-threat-detector

In [4]:
df_url['url_length'] = df_url['URL'].str.len()
df_url['num_dots'] = df_url['URL'].str.count(".")
df_url[['URL', 'url_length', 'num_dots']].head()

                                                 URL  url_length  num_dots
0  nobell.it/70ffb52d079109dca5664cce6f317373782/...         225       225
1  www.dghjdgf.com/paypal.co.uk/cycgi-bin/webscrc...          81        81
2  serviciosbys.com/paypal.cgi.bin.get-into.herf....         177       177
3  mail.printakid.com/www.online.americanexpress....          60        60
4  thewhiskeydregs.com/wp-content/themes/widescre...         116       116

In [5]:
df_url['num_hyphens'] = df_url['URL'].str.count("-")
df_url[['URL','num_hyphens']].head()

                                                 URL  num_hyphens
0  nobell.it/70ffb52d079109dca5664cce6f317373782/...            4
1  www.dghjdgf.com/paypal.co.uk/cycgi-bin/webscrc...            2
2  serviciosbys.com/paypal.cgi.bin.get-into.herf....            1
3  mail.printakid.com/www.online.americanexpress....            0
4  thewhiskeydregs.com/wp-content/themes/widescre...            1

In [6]:
df_url['URL'].str.split('.').head()

0    [nobell, it/70ffb52d079109dca5664cce6f31737378...
1    [www, dghjdgf, com/paypal, co, uk/cycgi-bin/we...
2    [serviciosbys, com/paypal, cgi, bin, get-into,...
3    [mail, printakid, com/www, online, americanexp...
4    [thewhiskeydregs, com/wp-content/themes/widesc...
Name: URL, dtype: object

In [7]:
df_url['TLD'] = df_url['URL'].str.split('.').str[-1]
df_url[['URL', 'TLD']].head()

,URL,TLD
0,nobell.it/70ffb52d079109dca5664cce6f317373782/...,1&login_access=1322408526
1,www.dghjdgf.com/paypal.co.uk/cycgi-bin/webscrc...,php
2,serviciosbys.com/paypal.cgi.bin.get-into.herf....,dispatch35463256rzr321654641dsf654321874/href/...
3,mail.printakid.com/www.online.americanexpress....,html
4,thewhiskeydregs.com/wp-content/themes/widescre...,com/wp-content/themes/widescreen/includes/temp...

In [8]:
import math
from collections import Counter

def calculate_entropy(string):
    counts = Counter(string)
    length = len(string)
    probabilities = [count / length for count in counts.values()]
    entropy = -sum(p * math.log2(p) for p in probabilities)
    return entropy

In [9]:
df_url['entropy'] = df_url['URL'].apply(calculate_entropy)

In [10]:
df_url['TLD'].nunique()

282403

In [11]:
df_url[['URL', 'TLD']].sample(10)

,URL,TLD
492514,s3-ap-southeast-1.amazonaws.com/onekeysdk/down...,apk
217305,murphysingriffintown.blogspot.com/,com/
41443,jnsensi.com/images/?ref=us.battle.net/d3/en/index,net/d3/en/index
7618,realnoob.com/Pagos/Paypal/Acceptpayment/Id/234...,htm
164681,diccionario.sensagent.com/Arras/en-en/,com/Arras/en-en/
287796,bartleby.com/60/122.html,html
153008,braxio.splinder.com/,com/
382349,manta.com/c/mm01tw9/actors-theatre-ensemble-of-oh,com/c/mm01tw9/actors-theatre-ensemble-of-oh
79715,www.orange-carb.org/SkeyCalc/,org/SkeyCalc/
329105,facebook.com/pages/Federation-CJA/112909312056192,com/pages/Federation-CJA/112909312056192

In [12]:
df_url['domain'] = df_url['URL'].str.split('/').str[0]

In [13]:
df_url[['URL', 'domain']].sample(10)

,URL,domain
188002,finance.yahoo.com/q/ud?s=UFS,finance.yahoo.com
381091,lyricstime.com/david-usher-closer-lyrics.html,lyricstime.com
465042,wingingitinmotown.com/2011/9/15/2426417/know-t...,wingingitinmotown.com
429402,seochat.com/c/a/Search-Engine-Optimization-Hel...,seochat.com
443909,thecanadianencyclopedia.com/index.cfm?PgNm=TCE...,thecanadianencyclopedia.com
490172,stagaman.comyr.com/php/index.php,stagaman.comyr.com
33295,krotzons.com/pCntrlde/webscr_prim.php?sdr01=aX...,krotzons.com
11655,restorehelprecovery.indonesian-hacker.net/plea...,restorehelprecovery.indonesian-hacker.net
121047,naszainspiracja.pl/wp-content/Google/,naszainspiracja.pl
136893,seisuikai.net/img/1/NavyPageOne.htm,seisuikai.net

In [14]:
df_url['TLD'] = df_url['domain'].str.split('.').str[-1]

In [15]:
df_url['TLD'].nunique()

1580

In [16]:
df_url['TLD'].value_counts().head(20)

TLD
com     361588
org      48628
net      23432
ca       10886
edu      10060
uk        8479
ru        6190
info      4366
br        4113
au        4081
de        3182
gov       3038
pl        2686
biz       2319
in        2185
it        2113
us        1851
cn        1800
fr        1747
mx        1508
Name: count, dtype: int64

In [17]:
top_tlds = df_url['TLD'].value_counts().head(15).index
df_url['TLD_grouped'] = df_url['TLD'].apply(lambda x: x if x in top_tlds else 'other')

In [18]:
df_url['TLD_grouped'].value_counts()

TLD_grouped
com      361588
other     54113
org       48628
net       23432
ca        10886
edu       10060
uk         8479
ru         6190
info       4366
br         4113
au         4081
de         3182
gov        3038
pl         2686
biz        2319
in         2185
Name: count, dtype: int64

In [19]:
df_encoded = pd.get_dummies(df_url, columns=['TLD_grouped'], prefix='tld')

In [20]:
df_encoded.columns.tolist()

['URL',
 'Label',
 'url_length',
 'num_dots',
 'num_hyphens',
 'TLD',
 'entropy',
 'domain',
 'tld_au',
 'tld_biz',
 'tld_br',
 'tld_ca',
 'tld_com',
 'tld_de',
 'tld_edu',
 'tld_gov',
 'tld_in',
 'tld_info',
 'tld_net',
 'tld_org',
 'tld_other',
 'tld_pl',
 'tld_ru',
 'tld_uk']